### ISSUE TITLE
Incompatible with Chrome 50

### ISSUE THREAD

**Issue by axquired24** [TaylanTatli/Moon#28] opened 2016-05-27 10:18 UTC
Please check with chrome browser v50 on windows

Thanks :smile:

**Comment by TaylanTatli** [comment] 2016-05-27 19:54
I'm a Linux user, so I can't check on Windows but there is no problem with Chrome v50 on Linux. Can you show me a screenshot?

**Comment by axquired24** [comment] 2016-05-28 17:07
When using Firefox in Linux or windows it's still amazing display. But with this is screenshot from chrome on windows. No Text visible.

![image](https://cloud.githubusercontent.com/assets/9043550/15628666/0500ad1e-2531-11e6-84c7-e436a9f58314.png)

**Comment by TaylanTatli** [comment] 2016-05-28 17:41
It's weird. Is it same for [taylantatli.me/Moon](http://taylantatli.me/Moon/)?

Ignore that error, it's disqus script. I forgot disabling comments for homepage, fixed now.

**Comment by axquired24** [comment] 2016-05-29 23:46
Yes it is the duplicate of taylantatli.me/Moon
that page looks same in windows chrome browser 
![image](https://cloud.githubusercontent.com/assets/9043550/15636705/13392eea-2632-11e6-819f-d1f7654ff387.png)

**Comment by TaylanTatli** [comment] 2016-05-30 00:30
I can't reproduce this bug. I tested it with my friend's laptop (v50 on Windows) and it's still ok. Also tested with browserstack.com and it's ok too. Can it be some problem with your Chrome browser profile or something?

**Comment by axquired24** [comment] 2016-05-31 01:33
Yes i'm sorry, i think my chrome look like crash on beta. Thanks for feedback

Keep up good work :+1:

**Closed** 2016-05-31 06:05 UTC
Labels: invalid
