### ISSUE TITLE
Github button isn't removed.

### ISSUE THREAD

**Issue by nikhiljolly** [TaylanTatli/Moon#54] opened 2016-08-11 14:39 UTC
Hello TaylanTatli,

I tried removing the github button on the home page via the _config.yml file.

I commented the line with respect to the github link. However, the button still appears on the home page.

Also, the button has the following link:
http://github.com/Jekyll::GitHubMetadata::MetadataDrop

Kindly resolve this issue if possible.

PS: Thanks for the amazing theme! :)

**Comment by libeclipse** [comment] 2016-08-31 18:39
You've probably accidentally changed some file but I cannot really check since it doesn't seem to be on your website.

**Comment by nikhiljolly** [comment] 2016-08-31 20:04
Well, I did consider that. So, I forked a new version and just commented the line with respect to the github link. And still the problem persists.

Then I resolved the issue by renaming the 'site.github' variable to something else. And it worked.
I think it might have something to do with this: https://help.github.com/articles/repository-metadata-on-github-pages/

**Comment by nikhiljolly** [comment] 2016-08-31 20:05
PS: My website isn't using this theme anymore.

**Comment by libeclipse** [comment] 2016-08-31 21:09
Please close this issue then if it's no longer relevant.

**Comment by nikhiljolly** [comment] 2016-08-31 21:21
Don't you think it is still relevant as the issue isn't actually resolved?
I did find a workaround but the issue still exists in the theme itself.

**Comment by libeclipse** [comment] 2016-08-31 21:33
I'm not too sure. I myself have never encountered the issue or anything
similar. If you're sure it wasn't an error you made then fair enough.

On 31 Aug 2016 22:21, "Nikhil Jolly" <notifications@github.com> wrote:

Don't you think it is still relevant as the issue isn't actually resolved?
I did find a workaround but the issue still exists in the theme itself.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/TaylanTatli/Moon/issues/54#issuecomment-243906228>, or mute
the thread

**Comment by ToddMurphy92** [comment] 2016-10-02 12:24
I'm also getting this issue with http://toddmurphy.me/ which is running this theme currently. Only things I have changed is the config and navigation .yml files.

**Comment by nikhiljolly** [comment] 2016-10-02 12:31
Hey @ToddMurphy92 ,
The issue does exist. Like I said before, I think it has something to do with using the 'site.github' name for the variable. Try renaming the variable to something else and replacing it wherever it is being used in the theme. At least that's how I fixed it.

**Comment by ToddMurphy92** [comment] 2016-10-02 12:34
In the creators defence you did say you were no longer using the theme, and so there's not much point in fixing something that doesn't impact anyone (or at least not anyone the dev knows of).

Thanks for the update though. I'll give that a shot, I'll let you know how I go (probably horribly, I'm pretty bad when it comes to git and all things coding).

**Comment by ToddMurphy92** [comment] 2016-10-02 12:39
So I had a quick look into removing 'site.github' variable/references and decided I'll just leave this as is and see what the dev says if/when they respond. This isn't really urgent for me, my site doesn't get much traffic and on the rare occasion it does it's unlikely to be from anyone who would be interested in seeing git.

**Comment by nikhiljolly** [comment] 2016-10-02 12:39
@ToddMurphy92 Haha.. yeah. I am not trying to attack or something. It's a thin line, I have a workaround but the issue still exists. :P

**Comment by nikhiljolly** [comment] 2016-10-02 12:49
@ToddMurphy92 Aah okay. I don't really have it on my system to give it a go. But in case you would like to quickly try, I think you need to mainly change it here: https://github.com/ToddMurphy92/ToddMurphy92.github.io/blob/master/_includes/social-links.html

**Comment by ToddMurphy92** [comment] 2016-10-02 12:57
That did indeed 'fix' the issue for the main page. Still shows up in the about bar though.

**Comment by ToddMurphy92** [comment] 2016-10-02 12:58
Modified nav.html, fixed the about bar issue :)

**Comment by nikhiljolly** [comment] 2016-10-02 12:59
Yay! Guess, you know now what to do!

PS: I was about to give you a hint. xD

**Comment by libeclipse** [comment] 2016-10-02 19:07
Actually yeah I never tried to remove the github button.

As for @taylantatli, he's currently in exam seasons without a PC, so it's unlikely there'll be any fixes any time soon. Might be worth asking for commit rights.

**Comment by theramiyer** [comment] 2016-11-27 05:56
Hey, all, the issue does exist. When running this locally using Jekyll, the GitHub button doesn't show if the username is removed. When hosting on GitHub Pages, the button shows, and hovering over the button shows `http://github.com/{`.

**Comment by TaylanTatli** [comment] 2016-12-22 17:07
It should be fixed with cd451e32c7446f57a1a3cec8f43887074d781d31. It was because of Github Metadata.

**Closed** 2016-12-22 17:07 UTC
Labels: bug
